### ISSUE TITLE
rcc has crash bug in the framework now

### ISSUE THREAD

**Issue by shuaimu** [msmummy/rococo#18]
happens /home/shuai/bworkspace/baroque/deptran/rcc/dep_graph.cc:55

<pre>
uint64_t DepGraph::sub_txn_graph(
        uint64_t tid,
        GraphMarshaler &gra_m
) {
    gra_m.gra = &txn_gra_;

    Vertex<TxnInfo> *source = txn_gra_.FindV(tid);
<b>
    verify(source != NULL);
</b>
    // Log::debug("compute for sub graph, tid: %llx parent size: %d",
    //     tid, (int) source->from_.size());

    auto &ret_set = gra_m.ret_set;

    find_txn_anc_opt(source, ret_set);
    ret_set.insert(source);
    return ret_set.size();
}
</pre>

**Comment by zhaoguowang** [comment]
dasfaewfdwsafcaf nklrevnlk;qnmkclerwMfl;
dsam,cl;
wekfjo;eqwrj'r;ofmq;rw

2015-10-20 19:08 GMT-04:00 Shuai <notifications@github.com>:

> happens /home/shuai/bworkspace/baroque/deptran/rcc/dep_graph.cc:55
>
> uint64_t DepGraph::sub_txn_graph(
>         uint64_t tid,
>         GraphMarshaler &gra_m
> ) {
>     gra_m.gra = &txn_gra_;
>
>     Vertex *source = txn_gra_.FindV(tid);*
>     verify(source != NULL);
> *
>     // Log::debug("compute for sub graph, tid: %llx parent size: %d",
>     //     tid, (int) source->from_.size());
>
>     auto &ret_set = gra_m.ret_set;
>
>     find_txn_anc_opt(source, ret_set);
>     ret_set.insert(source);
>     return ret_set.size();
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msmummy/rococo/issues/18>.
>



-- 
Best,
Zhaoguo Wang
