### ISSUE TITLE
Receive SIGSEGV at random places when calling malloc

### ISSUE THREAD

**Issue by shuaimu** [msmummy/rococo#20]
A possible place is
./rrr/rpc/marshal.hpp :34

<pre>
        raw_bytes(size_t sz = min_size) {
            size = std::max(sz, min_size);
<b>            ptr = new char[size]; </b>
        }
</pre>

**Comment by shuaimu** [comment]
another possible place is 
./rrr/rpc/server.cpp: 154

<pre>
            Request* req = new Request;
            verify(req->m.read_from_marshal(in_, packet_size) == (size_t) packet_size);
            v64 v_xid;
            req->m >> v_xid;
            req->xid = v_xid.get();
            <b>complete_requests.push_back(req); </b>
</pre>

**Comment by shuaimu** [comment]
another possible place is
./deptran/rcc_rpc.h: 383

<pre>
        std::vector<rrr::i32>* in_1 = new std::vector<rrr::i32>;
</pre>

**Comment by shuaimu** [comment]
another possible place is
./deptran/rcc_rpc.h: 385

<pre>
        rrr::i32* out_0 = new rrr::i32;
</pre>

**Comment by shuaimu** [comment]
another possible place is
./deptran/rcc_rpc.h: 408

<pre>
        rrr::DeferredReply* __defer__ = new rrr::DeferredReply(req, sconn, __marshal_reply__, __cleanup__);
</pre>

**Comment by shuaimu** [comment]
./deptran/rcc_rpc.h: 364

<pre>
        rrr::i32* out_0 = new rrr::i32;
</pre>

**Comment by shuaimu** [comment]
seems caused by this:
https://github.com/msmummy/rococo/commit/2682d16b73f98b9940aa529b0e08eb3dd782d310

**Comment by shuaimu** [comment]
may be also caused by some wrongful use of scope locks. seems solved

**Comment by lamontnelson** [comment]
Yes, I believe the segfault was fixed by this commit: https://github.com/msmummy/rococo/commit/5b31d5f4f50eef15bca84f0ce680703d05f55fff

The second error where transactions were being committed before all the pieces are done was fixed with this one:
https://github.com/msmummy/rococo/commit/737d3b4721e0b41813100dda2855d11078f86e39
