### ISSUE TITLE
Add ro6 into the test script

### ISSUE THREAD

**Issue by shuaimu** [msmummy/rococo#3]
The [run_all.sh](https://github.com/msmummy/rococo/blob/master/run_all.sh) is the script to run a set of tests on NYU beaker cluster with different protocols and generate the results for plotting. The current vesion includes 2PL/OCC/Rococo, but not RO6.

Another similar script [kodiak_run_all.sh](https://github.com/msmummy/rococo/blob/master/kodiak_run_all.sh), do the same thing, but on the Kodiak testbed.

The first (and necessary) task is to add ro6 into both scripts. 

The second (mostly necessary) task is to merge the two scripts and make it adaptable (configurable) to any test environments.

The third (very much preferable) task is to rewrite the script with python or ruby and make it easier to read and modify. Personally I prefer ruby, because it is easier to call a bash command in ruby (ret = `ls -al`), and a lot of other stuff. But python is okay too (if using python, plz make sure it is 2.7 compatible.)

**Comment by wlloyd** [comment]
Is there something like salt\* for ruby?

*http://saltstack.com/

**Comment by shuaimu** [comment]
I did a little search and found two ruby projects that might be very similar to SaltStack:

Puppet: https://puppetlabs.com/
Chef: https://www.chef.io/chef/

**Comment by shuaimu** [comment]
there seems to be a fourth option: Ansible

http://www.infoworld.com/article/2609482/data-center/data-center-review-puppet-vs-chef-vs-ansible-vs-salt.html

**Comment by shuaimu** [comment]
https://www.youtube.com/watch?v=T56uN6N_hs0

**Comment by shuaimu** [comment]
Added
